parameters:
  orders-create-new:
    in: body
    name: body
    required: true
    schema:
      type: object
      properties:
        data:
          type: object
          required:
            - type
          properties:
            type:
              type: string
              example: 'orders'
            attributes:
              $ref: '#definitions/OrderAttributes'
  orders-update-exist:
    in: body
    name: body
    required: true
    schema:
      type: object
      properties:
        data:
          type: object
          required:
            - type
          properties:
            type:
              type: string
              example: 'orders'
            id:
              type: integer
              example: 6
            attributes:
              $ref: '#definitions/OrderAttributes'
  orders-filter:
    in: body
    name: body
    required: true
    schema:
      type: object
      properties:
        page:
          type: object
          properties:
            limit:
              type: integer
              example: 100
            offset:
              type: integer
              example: 0
        fields:
          type: object
          properties:
            orders:
              type: array
              items:
                type: array
              example: ['price', 'amount', 'type']
        sort:
          type: array
          items:
            type: array
          example: ['-price']

